server {
  listen 80;
  server_name 44.214.199.224;

  return 301 https://$server_name$request_uri;
}


server {
  listen 443 ssl;
  server_name 44.214.199.224;

  ssl_certificate /etc/ssl/certs/selfsigned.crt;
  ssl_certificate_key /etc/ssl/private/selfsigned.key;

  types {
    text/html html htm;
    text/css css;
    application/javascript js mjs;
  }

  location / {
    root   /usr/share/nginx/html;
    index  index.html;
    try_files $uri $uri/ /index.html;
  }

  location /landing/ {
    root   /usr/share/nginx/html;
    index  index.html;
    try_files $uri $uri/ =404;
  }
}
